### ISSUE TITLE
Go to https

### ISSUE THREAD

**Issue by danmackinlay** [synestize/synestizer#26]
New Chrome versions break horribly. Checking the debug log, it seems to be about the new Chrome HTTP deprecation. We need to go to HTTPS, both on online and offline versions.
![screen shot 2015-06-03 at 14 29 21](https://cloud.githubusercontent.com/assets/21740/7959941/21939aa4-09fd-11e5-9370-1929bc4331d4.png)

**Comment by danmackinlay** [comment]
So - getUserMedia() now only works over HTTPS, and other things are to be disabled shortly too.

**Comment by danmackinlay** [comment]
A great argument for #25, where we don't have SSL problems (different problems, at least)

A clear modern intro to SSL certs is: https://devcenter.heroku.com/articles/ssl-certificate-self

The main question is - should we give people a nonsense self-signed certificate, or produce our own?

We _could_ also buy an SSL certificate - this might be worth it for synestizer.com. but for testing we need an alternative.

Moreover, as far as I know, SSL certificates only apply to a single domain, right? So we would in theory have to have a new certificate for www.synestizer.com, purple.synestizr.com, green.synestizer.com etc. 

Brrrrr.

**Comment by danmackinlay** [comment]
More in-depth version: http://stackoverflow.com/a/10176685

```
openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 1001 -subj '/CN=localhost' -nodes
```

Makign this work in Chrome is [quite complex](http://stackoverflow.com/a/15076602) and it is reportedly completely impossible on Android - so the fake certificate won't solve our problem

**Comment by danmackinlay** [comment]
OK, a self-signed certificate makes this work in OSX, but as far as I can tell, this doesn't work with the python simplehttpserver any more, OR the default Mongoose server, which supports SSL but doesn't seem to come with the right compilation options.

Nor does this fix the problem with synestizer.com...

**Comment by stahlnow** [comment]
I generated a self-signed certificate and configured a forward for synestizer.com, beta is also working under https://beta.synestizer.com/ (without automatic forward).  still need to buy a certificate that is more user friendly.

**Comment by stahlnow** [comment]
commercial ssl certificate is now activated.
