### ISSUE TITLE
Move Wiki into a documentation site

### ISSUE THREAD

**Issue by danmackinlay** [synestize/synestizer#5]
Because github's wiki is crap

**Comment by synestizer-docs** [comment]
You can edit this at the moment using http://prose.io/ - we still need a FAQ about that, and an automated documentation update script.

**Comment by synestizer-docs** [comment]
configuration information for prose.io is here: https://github.com/prose/prose/wiki/Prose-Configuration

**Comment by synestizer-docs** [comment]
Kaspar would also like to know how to update the faq.html automatically. My suggestion: custom domain for only the documents. (better for google search results!)

**Comment by synestizer-docs** [comment]
github pages documentation here: https://help.github.com/categories/github-pages-basics/

**Comment by danmackinlay** [comment]
OK, NOW the editor is online here:

http://prose.io/#synestize/synestizer/tree/gh-pages

site address here:

https://synestize.github.io/synestizer/

We need to make it a little bit prettier... but it's a start.

**Comment by danmackinlay** [comment]
Let's talk about making it prettier somewhere else ;-)

**Comment by Kultkat** [comment]
My dears, 

thank you for yesterday!!! I`m already looking forward to the next meeting, 
meanwhile I wrote to the appaward people of the zkm, their form doesn`t allow non-(android or iOS) apps
to participate, so maybe we have to move on.
for instance to this:http://node.vvvv.org/call-for-artists-nodetadaex-residency-program/
this or next year :-) 

Also I made the little poster for my friend eveline, which I attach, 
and yes, thanks for the changes yesterday...

Maybe Christoph you can push it when you are done, then the images are back online in the FAQs
thanks
Kaspar

Am 01.05.2015 um 18:50 schrieb dan mackinlay notifications@github.com:
